set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-option -sg escape-time 10
set-option -g focus-events on

set-option -sa terminal-overrides ',xterm*:Tc'
set-window-option -g mode-keys vi

bind C-c run "tmux save-buffer - | pbcopy"
bind C-v run "tmux set-buffer "$(pbpaste)"; tmux paste-buffer"

bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
