---
env: dev
logging:
  path: /tmp/delivery.log
fluentd:
  host: infra
  port: 24224
  network: tcp
  json: true
  tag: my.logs 
grpc:
  port: 50051
nats:
  url: "nats://infra:4222"
mongodb:
  uri: "mongodb://delivery:delivery@infra:27017/delivery"
